columnSuffix: svimcfao
contentColumnType: datetime
fieldGroup: da1d4526-3f54-4890-bcae-4d569b18dc7a # Common
handle: date
instructions: null
name: Datum
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: false
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
