field: 225e2c06-2164-4773-ba48-8967c3e93bbe # Inhaltsmodule
fieldLayouts:
  f073fad1-d86b-42de-997c-6303603be7dc:
    tabs:
      -
        elementCondition: null
        name: Content
        uid: eaf62f8e-05fa-4a3d-b126-f3337235a3d2
        userCondition: null
handle: accordion
name: Accordion
sortOrder: 2
